const books=[
  {
    title:'斗破苍穹',
    author:'天蚕土豆',
    id:'asdasd',
    updateTime:'2012-1-2'
  },
  {
    title:'斗破苍穹',
    author:'天蚕土豆',
    id:'asdasd',
    updateTime:'2012-1-2'
  },
  {
    title:'斗破苍穹',
    author:'天蚕土豆',
    id:'asdasd',
    updateTime:'2012-1-2'
  },
  {
    title:'斗破苍穹',
    author:'天蚕土豆',
    id:'asdasd',
    updateTime:'2012-1-2'
  },
  {
    title:'斗破苍穹',
    author:'天蚕土豆',
    id:'asdasd',
    updateTime:'2012-1-2'
  },
  {
    title:'斗破苍穹',
    author:'天蚕土豆',
    id:'asdasd',
    updateTime:'2012-1-2'
  },{
    title:'斗破苍穹',
    author:'天蚕土豆',
    id:'asdasd',
    updateTime:'2012-1-2'
  },{
    title:'斗破苍穹',
    author:'天蚕土豆',
    id:'asdasd',
    updateTime:'2012-1-2'
  }
]
const bookDetails=[{
  id:'asd',
  title:'元尊',
  author:'天蚕土豆',
  poster:'http://r.i.biquge5200.com/cover/aHR0cDovL3N0YXRpYy56b25naGVuZy5jb20vdXBsb2FkL2NvdmVyL2ZlLzk4L2ZlOThiNjhmMDYyN2VlMmIxZmVmMWI0NzhhOTgzNWNjLmpwZWc=',
  des:'吾有一口玄黄气，可吞天地日月星。',
  updateTime:'2017-11-03'
}]
export default {
  books,
  bookDetails
}